### ISSUE TITLE
Possiblity of adding wxpython

### ISSUE THREAD

**Issue by smac89** [arcolinux/arcolinux_repo_3party#2]
In the mainline repos for archlinux, they have not updated this [package](https://archlinux.org/packages/community/x86_64/python-wxpython/) in almost a year now, even though it is marked as outdated

Is it possible for you to add this package to this repo?

**Comment by arcolinuxz** [comment]
Will check it out further
looks interesting

cheers
erik

**Comment by smac89** [comment]
bump! Any luck @erikdubois ?

**Comment by erikdubois** [comment]
why would I add it 

it is on the Arch Linux repository

**Comment by smac89** [comment]
Good point but like I said, it has not been updated for a while and the arch devs aren't really forthcoming as to the reason why. In any case, no problem. We will just have to wait for them to decide when to update or for those of us who have the time, we will just build from source

**Comment by arcolinuxz** [comment]
I remember again - looked into it - was some kind of issue and I went about my day.
