### ISSUE TITLE
Quickemu package doesn't include OVFM patch for arch linux

### ISSUE THREAD

**Issue by Lautron** [arcolinux/arcolinux_repo_3party#7]
I recently installed `quickemu` from the arcolinux_repo_3party and encountered the following error:
```
ERROR! EFI boot requested but no EFI firmware found.
       Please install OVMF firmware."
```
I checked quickemu script and seems that the version from arcolinux_repo_3party doesn't include the [patch to fix OVMF on Arch Linux](https://github.com/quickemu-project/quickemu/commit/d0ae72a2510f52ae4a9181d7c65f2c69636ca298), even though it’s supposed to be the latest version. 

I installed the AUR version and it worked without issues:
```
paru -a quickemu
```

PS: Thanks for all the work you put into this project!

**Comment by arcolinuxz** [comment]
thanks for reporting
new package now online
added this one to the 'special packages'

**Comment by arcolinuxz** [comment]
https://youtu.be/_NmOfXckdf4
